import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DesktopNav from "@/components/DesktopNav";
import MobileNav from "@/components/AppComomponents/MobileNav";
import AppBar from "@/components/AppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
    <div id="PARENT-CONTAINER" className=" h-screen w-screen CENTER">

      <div id="LEFT-SECTION" className=" h-screen  ">

      <DesktopNav/>
      </div>

      <div id="RIGHT-SECTION" className=" relative flex-1 h-screen flex flex-col w-[80%]">

<div id="TOP-SECTION"> <AppBar/></div>

<div id="BOTTOM-SECTION" className=" w-[100%] relative  flex-1 "> 

{children}

</div>


</div>


  {/* 

 

<MobileNav/> */}

    </div>
      
        
        </body>
    </html>
  );
}
